name: tunbert-torch
channels:
  - pytorch
  - default
dependencies:
  - python=3.7.9
  - black=19.3b0
  - flake8=3.8.4
  - isort=5.6.4
  - pytorch=1.7.1
  - numpy=1.19.1
  - pip=20.2.2
  - torchvision=0.8.2
  - torchtext=0.8.1
  - cudatoolkit=11.0
  - pip:
      - nemo_toolkit[all]==1.0.0b1
      - pytorch-lightning==0.9.0
      - pre-commit==2.7.1
      - omegaconf==2.0.1rc12
      - hydra-core==1.0.0rc4
      - transformers==3.1.0