name: tunbert-tf2

dependencies:
  - python=3.7.9
  - black=19.3b0
  - flake8=3.8.4
  - isort=5.6.4
  - numpy=1.19.1
  - pip=20.2.2
  - cudatoolkit=11.0
  - pip:
      - pre-commit==2.7.1
      - tensorboard==2.5.0
      - tensorflow-gpu==2.5.0
